# Generated by Django 2.1.2 on 2018-10-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('incident_date', models.DateTimeField()),
                ('description', models.CharField(max_length=4096)),
                ('loss_amount', models.FloatField(null=True)),
                ('measures_taken', models.CharField(max_length=2048, null=True)),
                ('caterogy_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operrisk.Category')),
            ],
        ),
    ]
