# Generated by Django 2.0.5 on 2018-10-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='URL_name',
            field=models.CharField(default=models.CharField(max_length=256, unique=True), max_length=256, unique=True),
        ),
    ]
