# Generated by Django 2.0.5 on 2018-10-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0003_auto_20181018_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='URL_name',
            field=models.SlugField(unique=True),
        ),
    ]
