# Generated by Django 2.1.2 on 2018-10-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0005_auto_20181018_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='att',
            field=models.FileField(blank=True, upload_to='files_att'),
        ),
    ]
