# Generated by Django 2.1.2 on 2018-10-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0008_auto_20181019_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(),
        ),
    ]
