# Generated by Django 2.1.2 on 2018-10-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0014_remove_incident_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='created_date',
        ),
    ]
