# Generated by Django 2.1.2 on 2018-10-23 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operrisk', '0015_remove_incident_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='measures_taken',
            field=models.CharField(max_length=2048),
        ),
    ]
