# Generated by Django 2.1.2 on 2018-10-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0016_auto_20181023_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
