# Generated by Django 2.1.2 on 2018-11-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0017_auto_20181026_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
