# Generated by Django 2.1.2 on 2018-11-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0021_auto_20181105_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('1', 'Черновик'), ('2', 'Создан'), ('3', 'Утвержден'), ('4', 'Помечен как ошибка')], default='1', max_length=1),
        ),
    ]
