# Generated by Django 2.1.2 on 2018-11-06 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0022_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(default=datetime.date(2018, 11, 6)),
        ),
    ]
