# Generated by Django 2.1.2 on 2018-11-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0023_auto_20181106_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('URL_name', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operrisk.Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
    ]
