# Generated by Django 2.1.2 on 2018-11-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0024_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='operrisk.Subcategory'),
        ),
    ]
