# Generated by Django 2.1.2 on 2018-11-08 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0026_auto_20181106_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(default=datetime.date(2018, 11, 8)),
        ),
    ]
