# Generated by Django 2.1.2 on 2018-11-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0028_auto_20181108_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('1', 'Черновик'), ('2', 'Создан'), ('3', 'Утвержден'), ('4', 'Помечен как ошибка')], default='1', max_length=1),
        ),
    ]
