# Generated by Django 2.1.2 on 2018-11-15 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0029_auto_20181108_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_end_date',
            field=models.DateField(default=datetime.date(2018, 11, 15)),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(default=datetime.date(2018, 11, 15)),
        ),
    ]
