# Generated by Django 2.1.2 on 2018-11-15 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0030_auto_20181115_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_balance_date',
            field=models.DateField(default=datetime.date(2018, 11, 15), null=True),
        ),
    ]
