# Generated by Django 2.1.2 on 2018-11-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0031_incident_incident_balance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_balance_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
