# Generated by Django 2.1.2 on 2018-11-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0032_auto_20181115_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='comment',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
