# Generated by Django 2.1.2 on 2018-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operrisk', '0033_incident_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
